hydra:
  run:
    dir: .
  output_subdir: null
  job_logging:
    root:
      level: INFO
      handlers: [console]  # Only print to console, no file

base_save_path: /nfs/nhome/live/jheald/jax_dt/checkpoints

# load_dynamics_path: ${base_save_path}/2025-10-02/2r66wgba/dynamics_model_50000.pt
# load_CVLM_path: ${base_save_path}/2025-10-02/tikrinti/vae_model_50000.pt
# load_control_path: ${base_save_path}/2025-10-02/6ruqhdo6/emp_model_100000.pt

# load_dynamics_path: ${base_save_path}/2025-09-30/k1p03qj2/dynamics_model_100000.pt
# load_CVLM_path: ${base_save_path}/2025-10-01/7d8rp9k1/vae_model_100000.pt

load_dynamics_path: null
load_CVLM_path: null
load_control_path: null

env_d4rl_name: D4RL/relocate/expert-v2

seed: 0
rtg_scale: 1000
rtg_target: null

context_len: 20
gamma: 0.95

controlled_variable: obj_pos
controlled_variables_dim: null
controlled_variables_idx: null

n_dynamics_ensembles: 5
h_dims_dynamics: [256, 256]
dynamics_dropout_rates: [0., 0.]
learn_dynamics_std: False

state_dependent_prior: False
h_dims_prior: [256, 256]

horizon_embed_dim: 128
h_dims_posterior: [256, 256]
posterior_dropout_rates: [0., 0.]

h_dims_GRU: 128
autonomous: False

dynamics_batch_size: 4096
vae_batch_size: 1024
emp_batch_size: 1024

lr: 1e-6
wt_decay: 1e-4
warmup_steps: 10_000
grad_updates_per_step: 1
gradient_clipping: 0.25

num_updates_per_iter: 100
max_train_iters: 1_000
dynamics_save_iters: 1_000
vae_save_iters: 1_000
emp_save_iters: 1_000

max_devices_per_host: null

n_rollouts: 3